### ISSUE TITLE
move away from the deprecated ArrayList type to Generic.List

### ISSUE THREAD

**Issue by LeeDailey** [thedavecarroll/PoShDynDnsApi#9]
**Describe the bug**
you use ...   
    
    $DynDnsHistory = New-Object System.Collections.ArrayList
    
... and the arraylist type has been deprecated. plus, it generates those silly `.Add()` counter items that need to be suppressed - and the Generic.List does not.

**To Reproduce**
    
    $DynDnsHistory = New-Object System.Collections.ArrayList
    
**Expected behavior**
     
    $DynDnsHistory = [System.Collections.Generic.List[object]]::new()

**Screenshots**
n/a

**PowerShell Environment (please complete the following information):**
 - OS = win7x64
 - Edition = desktop
 - Version = 5.1

**Additional context**
n/a

**Comment by thedavecarroll** [comment]
Lee, 
I updated this issue to replace the bug label with enhancement.

As stated on Reddit, I'll work on this when I get back to this module. 

Again, thanks for submitting this!
